### ISSUE TITLE
李老师，咨询下，box定投实践群现在还可以加入吗？

### ISSUE THREAD

**Issue by wangxiaofei888** [xiaolai/xiaolai.github.io#28]

**Comment by wwwxj123** [comment]
去交易所理财定投就可以了！

wangxiaofei888 ***@***.***>於 2022年5月27日 週五，07:03寫道：

**Comment by cheneyjian** [comment]
现在暂时关闭了 开放时间等通知

**Comment by cheneyjian** [comment]
本人已经续费了7年 现在暂时关闭入群，且入群方式做了调整，关闭前只需要下载app付钱就可以进群，现在是不仅进群需要邀请码，下载app也需要邀请，接着还需要考试通过后付款最终才能进群
总的来说虽然入群方式严格了 对想进入群的人来说都不是问题

**Comment by wwwxj123** [comment]
笑来的邮件怎么发这里了！这是我的邮箱
cheneyjian ***@***.***>於 2022年5月28日 週六，05:57寫道：
