### ISSUE TITLE
安装nvm碰到的问题

### ISSUE THREAD

**Issue by wungsen** [xiaolai/xiaolai.github.io#4]
https://github.com/xiaolai/xiaolai.github.io/blob/master/2016/06/16/makecs-basic-dev-env-settup/index.html

**问题:**
按照" nvm 和 node 4.4.5"章节，执行`brew install nvm`后，
再执行 nvm install 4.4.5 时, 报 --command not found

**解决:**
1.检查`~/.nvm`文件夹是否存在，若无，执行 `mkdir ~/.nvm` ,手动创建;

2.检查`~/.bash_profile` 文件中有无下面的两行，如果没有，手动加入:

> export NVM_DIR="~/.nvm" 
> [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

3.重新安装,这次用的:
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash`

**注意:**
1.把~/.nvm替换成实际路径；
2.更新配置文件后，要关闭terminal窗口，重新开启。

**Comment by richardzhengjunliu** [comment]
垃圾，都打不开啊
