### ISSUE TITLE
希望博客加入评论功能

### ISSUE THREAD

**Issue by tommyjiang** [xiaolai/xiaolai.github.io#7]
偶然发现笑来老师的博客，希望加入评论功能，方便大家交流。

另外，这一个月一直没更新，笑来老师是在忙别的事么？

**Comment by tardistao** [comment]
没想到笑来老师自己还搭建博客，想再博客里面留言发现没有评论栏，希望笑来老师加上，方便交流

**Comment by tommyjiang** [comment]
散了吧，提了半年多也没有反馈。
